---
title: "Exercise Benchmark Dose Modelling"
subtitle: "MVEN10 Risk Assessment in Environment and Public Health"
author: "Zheng Zhou"
format: html
editor: source
---

# Instructions

Welcome to the **Exercise** for the course *MVEN10*.
This exercise is designed to help you self-assess your understanding and application of key concepts discussed in the lectures.
Please read the instructions and the description of each knowledge point carefully before beginning the exercise.

## Exercise Details

- **Time Limit**: 60 minutes
- **Total Questions**: 2
- **Purpose**: To evaluate your comprehension and practical application of benchmark dose (BMD) modeling through software application.

## Knowledge Points Covered {.smaller}

1. **Dose**: Understand the concept of dose and its role in risks to human health and the environment; Understand the purpose of dose-response modeling.

2. **NOAEL/LOAEL**: Understand the concept of the NOAEL/LOAEL approach and how to derive a NOAEL/LOAEL given data; Understand the weaknesses of the NOAEL/LOAEL approach.

3. **BMD modeling**: Understand how the BMD approach addresses the weaknesses of the NOAEL/LOAEL approach and the three steps of BMD modeling and the strengths and weaknesses of BMD modeling

4. **BMD tools**: Become familiar with established BMD tools; Be able to run a BMD analysis with different tools.

# Exercise Questions

## Question 1: NOAEL/LOAEL

You are provided with a dose-response data set. The study has a control group and three dose groups. For each group, the following data is measured: number of subjects, group average response, group standard deviation, and the p value of the difference in average response compared with the control group. You can find the data by the file "example_data_dose_response.txt".

### Tasks

**(a)** *Explain* if this data can derive a NOAEL. If yes, what is it? If no, why?

**(b)** *Explain* if this data can derive a LOAEL. If yes, what is it? If no, why?
 
## Question 2: BMD modeling

Using the same dose-response data provided in question. Recall the three steps of BMD modeling. Perform the three steps in the existing BMD tools and generate reports.

### Tasks

**(a)** *Use* EFSA PROAST for BMD modeling. You can use the web version: [https://proastweb.rivm.nl/](https://proastweb.rivm.nl/) or the R-package version: [https://www.rivm.nl/en/proast](https://www.rivm.nl/en/proast). Generate a report.

**(b)** Based on the report from **(a)**, *find* the following information: 1) number of models fitted, 2) AIC of each model, 3) CED, CEDL and CEDU of each model

**(c)** *Use* US EPA BMDS for BMD modeling: [https://www.epa.gov/bmds/bmds-online](https://www.epa.gov/bmds/bmds-online). Generate a report.

**(d)** Based on the report from **(c)**, *find* the following information: 1) number of models fitted, 2) P-value, AIC and reason of recommendation of each model, 3) BMD, BMDL and BMDU of each model 
 
## Question 3: Evaluate dose-response models between NOAEL, LOAEL and the BMDs from different tools

Gather your results of NOAEL/LOAEL (Question 1) and BMDs from different tools (Question 2). 

### Tasks

*Discuss* one strengths and one weaknesses of the NOAEL/LOAEL approach and the BMD approach, respectively.

You may consider the following hints:

1. What information is needed for each approach?

2. If there are changes in study design, e.g., dose level setup, how will each approach be affected?

2. How difficult it is to implement each approach?

3. Does the sample size have impacts on the estimates from the two approaches?

4. Can a NOAEL be derived from a LOAEL? from a BMD? 

5. What is a benchmark response and how it is chosen?

6. What are the differences between BMD models?

7. How are uncertainty in the data considered in the two approaches?
