---
title: "Exercise 16. Species Distribution Modelling CLIMEX"
subtitle: "MVEN10 Risk Assessment in Environment and Public Health"
author: "Ullrika Sahlin"
---

## Exercise overview

### Background

The use of species distribution modeling to predict the possible extent of suitable habitat for significant pests has been accepted as an efficient method for determining effective management and countermeasures. [CLIMEX](https://www.hearne.software/Software/CLIMEX-DYMEX/Editions) and [MaxEnt](https://biodiversityinformatics.amnh.org/open_source/maxent/) are widely used software for creating species distribution models. CLIMEX predicts climatic suitability of a specific region for target species, whereas MaxEnt uses various environmental variables with presence-only data to assess potential distribution.

Bioclimatic modelling use species occurrence data to model distribution or perform climate matching. 

The Global Biodiversity Information Facility [https://www.gbif.org/](https://www.gbif.org/) is an database for species occurrence data. 

<!-- https://rpubs.com/fidele98/sdm -->

<!-- https://damariszurell.github.io/SDM-Intro/ -->

<!-- https://www.climond.org/Default.aspx -->


### Purpose

- To perform climate matching to assess establisment potential for a potentially invasive species



### Content

-   

The group that are to do CLIMEX will get a licence for CLIMEX for a personal computer - it costs 10 US dollars [https://www.hearne.software/Software/CLIMEX-DYMEX/Editions](https://www.hearne.software/Software/CLIMEX-DYMEX/Editions)

Here in the exercise, we will use an online implementation of CLIMEX for New Zealand [https://climate.b3nz.org.nz/](https://climate.b3nz.org.nz/)

### Duration

45 minutes

### Reporting

Be prepared to report back at the end of the exercise.

### References

Steven J. Phillips, Miroslav Dudík, Robert E. Schapire. [Internet] Maxent software for modeling species niches and distributions (Version 3.4.1). Available from url: [http://biodiversityinformatics.amnh.org/open_source/maxent/](http://biodiversityinformatics.amnh.org/open_source/maxent/). Accessed on 2023-9-19.

## Content

