project:
  type: website
  output-dir: docs

website:
  title: "MVEN10"
  sidebar:
    style: "docked"
    search: true
    contents: 
       - section: "General"
         contents:
         - text: "Probability distributions"
           file: ex/probability_distribution.qmd
           target: "_blank"
       - section: "Intro to excel and R - Sept 5"
         contents:
         - text: "Useful functions in Excel"
           file: ex/useful_functions.qmd
           target: "_blank"
         - text: "Intro to Quarto and R"
           file: ex/introduction_to_quarto_and_R.qmd
           target: "_blank"
         - text: "Useful functions in R"
           file: ex/useful_functions_with_R.qmd
           target: "_blank"
       - section: "Probability models - Sept 8"
         contents: 
         - text: "Interval and 1D Monte Carlo"
           file: ex/ex_daily_intake_equation.qmd
           target: "_blank"
         - text: "Exercise Probability"
           file: ex/chance_belief_frequency.qmd
           target: "_blank"
       - section: "Hazard and Exposure assessment - Sept 12" 
         contents: 
         - text: "Hazard"
           file: zheng/ex_hazard.qmd
           target: "_blank"
         - text: "Exposure"
           file: zheng/ex_exposure.qmd
           target: "_blank"
       - section: "Hazard characterisation - Sept 15" 
         contents: 
         - text: "Species Sensitivity Distribution"
           file: ex/ex_species_sensitivity_distribution.qmd
           target: "_blank"
       - section: "Hazard characterisation - Sept 22"
         contents:
         - text: "Benchmark dose modelling"
           file: zheng/ex_benchmark_dose_modelling.qmd
           target: "_blank"

      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

