project:
  type: website
  output-dir: docs

website:
  title: "MVEN10"
  sidebar:
    style: "docked"
    search: true
    contents: 
      - section: "Aug 30"
        contents:
        - text: "Exercise 1 45 min"
          file: ex/expressing_uncertainty.qmd
          target: "_blank"
        - text: "Exercise 2 45 min"
          file: ex/chance_belief_frequency.qmd
          target: "_blank"
        - text: "Exercise 3 45 min"
          file: ex/introduction_to_quarto_and_R.qmd
          target: "_blank"
      - section: "Sept 4"
        contents:
        - text: "Exercise 4 45 min"
          file: ex/risk_classification_ROC.qmd
          target: "_blank"
        - text: "Exercise 5 45 min"
          file: ex/expert_judgement.qmd
          target: "_blank"
        - text: "Wisdom of Crowds Ex 6"
          file: ex/wisdom_of_crowds.qmd
          target: "_blank"
        - text: "Exercise 6 45 min"
          file: ex/useful_functions.qmd
          target: "_blank"
      - section: "Sept 6"
        contents:  
        - text: "Useful functions in R"
          file: ex/useful_functions_with_R.qmd
          target: "_blank"
        - text: "Exercise 7"
          file: ex/observe_summarise.qmd
          target: "_blank"
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

