project:
  type: website
  output-dir: docs

website:
  title: "MVEN10"
  sidebar:
    style: "docked"
    search: true
    contents: 
      - section: "Aug 30"
        contents:
        - text: "Exercise 1"
          file: ex/expressing_uncertainty.qmd
          target: "_blank"
        - text: "Exercise 2"
          file: ex/chance_belief_frequency.qmd
          target: "_blank"
        - text: "Exercise 3"
          file: ex/introduction_to_quarto_and_R.qmd
          target: "_blank"
      - section: "Sept 4"
        contents:
        - text: "Exercise 4"
          file: ex/risk_classification_ROC.qmd
          target: "_blank"
        - text: "Exercise 5"
          file: ex/expert_judgement.qmd
          target: "_blank"
        - text: "Wisdom of Crowds Ex 6"
          file: ex/wisdom_of_crowds.qmd
          target: "_blank"
        - text: "Exercise 6"
          file: ex/useful_functions.qmd
          target: "_blank"
      - section: "Sept 6"
        contents:  
        - text: "Useful functions in R"
          file: ex/useful_functions_with_R.qmd
          target: "_blank"
        - text: "Exercise 7"
          file: ex/observe_summarise.qmd
          target: "_blank"
      - section: "Sept 11"
        contents:  
        - text: "Exercise 8"
          file: ex/observe_fit_simulate.qmd
          target: "_blank"
        - text: "Exercise 9"
          file: ex/ex_environ_exposure_assessment.qmd
          target: "_blank"
      - section: "Sept 13"
        contents:  
        - text: "Exercise 10"
          file: ex/ex_exposure_assessment_databases.qmd
          target: "_blank"
        - text: "Exercise 11"
          file: ex/ex_benchmark_dose_modelling.qmd
          target: "_blank"
        - text: "Exercise 12"
          file: ex/ex_daily_intake_equation.qmd
          target: "_blank"
      - section: "Sept 18"
        contents:  
        - text: "Exercise 13"
          file: ex/ex_daily_intake_equation_MC.qmd
          target: "_blank"
        - text: "Exercise 14"
          file: ex/ex_population_viability_analysis.qmd
          target: "_blank"
      - section: "Sept 19"
        contents:  
        - text: "Exercise 15"
          file: ex/ex_species_sensitivity_distribution.qmd
          target: "_blank"
        - text: "Exercise 16"
          file: ex/ex_species_distribution_modelling.qmd
          target: "_blank"
        - text: "Exercise 17. Assessment of overall uncertainty (video)"
      - section: "Oct 17"
        contents:  
        - text: "Exercise 18 Environmental health risk assessment (canvas)"
      - section: "Oct 18"
        contents: 
        - text: "Exercise 19"
          file: ex/ex_uncertainty_analysis.qmd
          target: "_blank"
        - text: "Exercise 20"
          file: ex/ex_bioaccumulation.qmd
          target: "_blank"
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

